#!/usr/bin/env python3
"""
OSTEOFLOW LANG VIRTUAL MACHINE
==============================
Purpose: Executes the pulse sequence generated by compiler.
Simulates how the real chip would behave.

Usage: python vm.py program.ofl
"""

import sys
import time

class OsteoflowVM:
    """
    Virtual Machine that "executes" voltage pulses.
    In reality, the chip just receives voltages.
    This VM simulates that process.
    """
    
    def __init__(self):
        self.program = []        # Pulse sequence
        self.pc = 0               # Program counter
        self.current_time = 0     # Simulation time (seconds)
        
    def load_program(self, pulses: list):
        """Load pulse sequence from compiler"""
        self.program = pulses
        
    def run(self, max_steps=1000):
        """
        Execute pulses sequentially.
        Each pulse is applied to the chip.
        """
        step = 0
        while self.pc < len(self.program) and step < max_steps:
            pulse = self.program[self.pc]
            
            # Simulate different pulse types
            if pulse['type'] == 'SET':
                print(f"[t={self.current_time*1e9:.0f}ns] ⚡ SET pulse: {pulse['voltage']}V {pulse['duration']*1e9:.0f}ns")
                
            elif pulse['type'] == 'RESET':
                print(f"[t={self.current_time*1e9:.0f}ns] ⚡ RESET pulse: {pulse['voltage']}V {pulse['duration']*1e9:.0f}ns")
                
            elif pulse['type'] == 'ACTUATE':
                print(f"[t={self.current_time*1e9:.0f}ns] 💊 ACTUATOR {pulse['actuator']}: {pulse['duration']*1e6:.1f}µs pulse")
                
            elif pulse['type'] == 'WAIT':
                self.current_time += pulse['duration']
                print(f"[t={self.current_time*1e9:.0f}ns] ⏱️  Wait {pulse['duration']*1e6:.1f}µs")
                
            self.pc += 1
            step += 1
            
        print(f"\n✅ Program executed in {self.current_time*1e3:.3f}ms")
        print(f"   Total pulses: {len(self.program)}")

# ==================== MAIN ====================
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python vm.py program.ofl")
        sys.exit(1)
        
    # Compile first
    from compiler import OsteoflowCompiler
    compiler = OsteoflowCompiler()
    pulses = compiler.compile(sys.argv[1])
    
    print(f"Compiled {len(pulses)} pulses")
    
    # Then run in VM
    vm = OsteoflowVM()
    vm.load_program(pulses)
    vm.run()